# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20170606_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizapplication',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer'),
        ),
        migrations.AlterField(
            model_name='quizapplication',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
