# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170606_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='possible_answers',
            field=models.ManyToManyField(blank=True, to='quiz.Answer'),
        ),
        migrations.AlterField(
            model_name='quizapplication',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer'),
        ),
    ]
